name: bhrastabusters
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental pub.dev publishing

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.1 # or latest version
  url_launcher: ^6.2.6
  #image_picker: ^1.0.4

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/twoflag.png
    - assets/pic1.jpeg
    - assets/pic2.jpg
    - assets/pic3.jpeg
    - assets/pic4.jpeg
    - assets/pic5.jpeg
