name: bhrastabusters
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.1
  url_launcher: ^6.2.6
  device_info_plus: ^11.4.0
  file_picker: ^10.2.0
  http: ^1.1.0
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/twoflag.png
    - assets/pic1.jpeg
    - assets/pic2.jpg
    - assets/pic3.jpeg
    - assets/pic4.jpeg
    - assets/pic5.jpeg
    - assets/pic6.png
    - assets/pic7.png
    - assets/pic8.png
    - assets/toppage.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/twoflag.png"
